- name: Add VBoxClient to xinitrc
  lineinfile: dest=$home_directory/.xinitrc regexp="^VBoxClient-All" line="VBoxClient-all &" insertbefore="^exec" create=yes

- name: Launch VBoxClient
  command: VBoxClient-all

- name: Enable vboxservice
  command: systemctl enable vboxservice.service
  sudo: true

- name: Start vboxservice now, for convenience
  command: systemctl start vboxservice.service
  sudo: true