- hosts: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2
    home_directory: /home/$username
  sudo: false
  user: $username
  tasks:
  - name: Install packages
    pacman: name=emacs,git,firefox update_cache=yes
    sudo: true

  - name: Copy in git config
    template: src=templates/git-config dest=$home_directory/.gitconfig

  - name: Download emacs settings
    git: repo=ssh://git@github.com/augustl/.emacs.d.git dest=$home_directory/.emacs.d

  - name: Update emacs settings submodules
    command: git submodule update --init chdir=$home_directory/.emacs.d

  - name: Copy in emacs config file
    copy: src=templates/emacs-config.el dest=$home_directory/.emacs.d/init.el
