- hosts: local
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2
    home_directory: /home/$username
    xfce4_term_conf: $home_directory/.config/xfce4/terminal
  sudo: false
  user: augustl
  tasks:
  - name: Install packages
    pacman: name=xorg-server,xorg-server-utils,xorg-xinit,i3,dmenu,mesa-libgl,ttf-inconsolata,bdf-unifont,ttf-dejavu,ttf-freefont,ttf-bitstream-vera,ttf-liberation,xfce4-terminal,gtk-engines,gnome-keyring update_cache=yes
    sudo: true

  - name: Copy in gtk2 config
    copy: src=templates/gtk2-config dest=$home_directory/.gtkrc-2.0

  - name: Create directories for xfcd4-terminal config
    file: state=directory path=$xfce4_term_conf recurse=yes

  - name: Copy in xfce4-terminal config file
    copy: src=templates/xfce4-terminal-config dest=$xfce4_term_conf/terminalrc

  - name: Copy in xfce4-terminal keymap config file
    copy: src=templates/xfce4-terminal-fontconfig.scm dest=$xfce4_term_conf/accels.scm

  - name: Copy in xinitrc
    copy: src=templates/xinitrc dest=$home_directory/.xinitrc
