- name: Install packages
  pacman: name=networkmanager,network-manager-applet update_cache=yes
  sudo: true

- name: Start nm-applet with xorg
  lineinfile: dest={{home_directory}}/.xinitrc regexp="^nm-applet" line='nm-applet &' insertbefore="^exec"