- name: Configure pacman to not care about slow networks, firewalls, etc
  sudo: true
  lineinfile: dest=/etc/pacman.conf regexp=^XferCommand line='XferCommand = /usr/bin/curl --speed-time 0 --silent -C - -f %u > %o' insertafter='^\[options\]'

- name: Install packages
  pacman: name=pm-utils
  sudo: true

- name: Copy in locale.gen config
  copy: src=locale.gen dest=/etc/locale.gen
  sudo: true

- name: Generate locale
  command: locale-gen
  sudo: true

- name: Copy in locale config
  copy: src=locale.conf dest=/etc/locale.conf
  sudo: true