- name: Install packages
  pacman: name=xf86-video-intel,xf86-input-synaptics,thinkfan
  sudo: true

- name: Set menu key to super
  lineinfile: dest={{home_directory}}/.xinitrc regexp="^\{ sleep 0\.5\; xmodmap" line='{ sleep 0.5; xmodmap -e "keycode 135 = Super_L NoSymbol Super_L" ; } &' insertbefore="^exec"

- name: Allow custom fan control
  lineinfile: dest={{thinkpad_acpi_conf}} regexp="^options\ thinkpad_acpi\ fan_control\=1" line="options thinkpad_acpi fan_control=1" create=yes
  sudo: true

- name: Enable thinkfan
  command: systemctl enable thinkfan
  sudo: true

- name: Copy in thinkfan config
  copy: src=thinkfan.conf dest=/etc/thinkfan.conf
  sudo: true